[tool.poetry]
name = "cboard"
version = "0.1.0"
description = ""
authors = ["1TaylanOzturk <1taylanozturk@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyperclip = "^1.8.2"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cboard = 'cboard:main'
